### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by janvandersleen** [glewe/ci4-auth#1]
Install instructions

Oops
$routes->group('', ['namespace' => 'CI4\Auth\Src\Controllers'], function ($routes) {

This works :-)
$routes->group('', ['namespace' => 'CI4\Auth\Controllers'], function ($routes) {

Typo!

regard JvdSl1

**Comment by glewe** [comment]
Hi there
and thanks for spotting. 
Fixed it just now.
Best regards,
George
