### ISSUE TITLE
Passwords cannot contain re-hashed personal information

### ISSUE THREAD

**Issue by MarcPinnell** [glewe/ci4-auth#12]
Getting this error on my first user registration and cannot figure out why. From what I can read into the code, it should not be triggering. Suggestions?

Email: marc@prime42.net
UserName: Marc
Password: 2ijkU0LJB5dB705!DFlvo$I   <-- I am not using this obviously (since I just posted it) but it is one that fails.

What in that password is "Personal"?

**Comment by glewe** [comment]
Hi @MarcPinnell ,

the "isNotPersonal()" check is done in
CI4\Auth\Authentication\Passwords\NothingPersonalValidator.php
I could not find anything that your password does not fulfill. Beats me.
That code is from the original [Myth-Auth](https://github.com/lonnieezell/myth-auth) library.

You can try to disable the NothingPersonal check by changing Auth.php:
```
public $passwordValidators = [
    'CI4\Auth\Authentication\Passwords\CompositionValidator',
    'CI4\Auth\Authentication\Passwords\NothingPersonalValidator',
    'CI4\Auth\Authentication\Passwords\DictionaryValidator',
    // 'CI4\Auth\Authentication\Passwords\PwnedValidator',
];
```
Comment out the NothingPersonalValidator.

Best regards,
George

**Comment by MarcPinnell** [comment]
Thanks for getting back to me @glewe . Loving the library. I'm planning on spending some time extending it a bit and will share when I get there. Mainly in the areas of forms and setup.
But anyway, the above issue has an interesting development that I forgot to come back and share. I think the error might be length related. If you cut that password in half (or so) then it works. Is there a length restriction or check somewhere?

**Comment by glewe** [comment]
Ok. Thanks for the info. The developer of that module might come up with a fix.
Best regards,
George
