### ISSUE TITLE
UserOptionModel

### ISSUE THREAD

**Issue by monster010** [glewe/ci4-auth#13]
heyho,

mag das Projekt, dachte aber ich weise kurz darauf hin, dass im User Entity ein UserOptionModel integriert ist, welches nicht exisistiert.

**Comment by glewe** [comment]
Yes, correct. Sorry for that.
I am using a simple option-value table to store user options. I added the stub to release v1.5.0. Feel free to use it. It is no0t a must.
Best regards,
George
