### ISSUE TITLE
Navbar dropdown not working in responsive mode

### ISSUE THREAD

**Issue by projectwehelp** [glewe/ci4-auth#16]
The navbar is not working in responsive mode.

PS: Very well documented and worked out of the box on the first attempt !

<img width="383" alt="Screenshot 2023-05-15 at 9 35 06 AM" src="https://github.com/glewe/ci4-auth/assets/78574989/3ea520aa-a1d4-488e-b237-096af041a7d4">

**Comment by glewe** [comment]
Hi @projectwehelp ,
thanks for the find. There was indeed a bug. Now fixed in 3.1.1.
Best regards,
George
