### ISSUE TITLE
Suggestion to add Magic link from Shield for login and verification 

### ISSUE THREAD

**Issue by projectwehelp** [glewe/ci4-auth#17]
Believe adding magic link ( from Shield) is easy and a wonderful addition to this great package

**Comment by glewe** [comment]
I haven't looked into that yet. Currently, you can use the 'Forgot password' feature. I hope to find some time soon to check it out...

**Comment by glewe** [comment]
I apologize for not having the time to deal with this. I will close this for now. Maybe there is a PR one day.
