### ISSUE TITLE
Bootstrap 5 Helper load

### ISSUE THREAD

**Issue by treborin** [glewe/ci4-auth#4]
Hi,
For the Authorization part views to work ok with bootstrap 5, you need to call bs5 helper. Otherwise views do not renders ok.
I did it including this line on every construct function of the Groups, Permissions, Roles and Users controllers:
`helper('bs5_helper');`

Thanks for the good job with CI4-Auth

**Comment by glewe** [comment]
Hi @treborin ,
thanks for the find. You are of course right. The bs5 helper needs to be loaded in order to make its functions work.
I have added a note about that to the readme file.
Best regards,
George
