### ISSUE TITLE
Creating a new user 

### ISSUE THREAD

**Issue by stezam** [glewe/ci4-auth#5]
Dear sir,
Thankyou for your Authentication software CI4-Auth I have started to use it and it is very helpful. 
It would be great if when I create a new user through the website itself as an administrator could force a reset password when the new user logs in the first time.

**Comment by glewe** [comment]
Hi @stezam ,
thanks for the flowers.
A good idea to send a password reset mail to a freshly created user. I added a config option "sendPasswordResetUponCreate". If set to true such a mail is sent when a new user is created.
Thanks for the idea. Best regards,
George

**Comment by stezam** [comment]
Thank you 
much appreciated

**Comment by stezam** [comment]
Tried but not working I am afraid. Sorry ):

**Comment by glewe** [comment]
Did you update all files? Especially the Auth.php config file and the UserController. I tested locally and the mail send is triggered.

**Comment by stezam** [comment]
Dear Sir 
I am sorry for the inconvenience but it was my fault.  Fixed the issue and it works perfect.  Well Done. Thank you once again.

**Comment by glewe** [comment]
Hi @stezam ,
I have slightly changed the implementation of this feature. I found that it might not be covering individual uses cases when the setting is global and cannot be chosen per user creation.
I now added a checkbox to the user creation form. When checked, the mail is sent. Otherwise it is not.
Best regards,
George

**Comment by stezam** [comment]
Thank you Sir will try later on and give you my feed back if I may.
Is it ok if in the future I can suggest more in my opinion improvements please as I do not want to sound demandig.
Thank you

**Comment by glewe** [comment]
Sure. Go ahead if you have ideas. Open a new issue though then.
