### ISSUE TITLE
Create User reset hash not set

### ISSUE THREAD

**Issue by stezam** [glewe/ci4-auth#6]
Dear Sir 
It seems that the updates for the create User are gone.
Something Happened?

**Comment by glewe** [comment]
Hi @stezam ,
not sure what you mean. I changed the feature. You now have a checkbox at the bottom of the user create screen. It allows you to send a password reset mail or not.
Best regards,
George

**Comment by stezam** [comment]
Yes that is very true.  I needed to use the project again so I downloaded the latest version 1.21.  The config file does not match the one on the previous version and the other thing is that when you click the the reset checkbox, the email is sent however the reset hash is not being created in the database and therefore the the email is not found in the database and gives the error that the email is not found.

**Comment by glewe** [comment]
Hmm, weird. I had to rearrange the code a bit in order to get the rest hash saved to the DB. Now it works in 1.2.2.

**Comment by stezam** [comment]
Thank you
