### ISSUE TITLE
Resend Activation Email

### ISSUE THREAD

**Issue by stezam** [glewe/ci4-auth#9]
Sorry to be a pest again.  There seem to be a problem when one asks to resend the activation email.  It seems that is not posting the token so it is always returning the error that account is not found.

Thanks 
Good Day

**Comment by glewe** [comment]
Please try 1.3.1. I might solve this one too.

**Comment by R3N3G** [comment]
Hi, test your script today, 
variable token is empty from Activate your account, example link:

 https://panel.cluster.pocketcloud.io/index.php/activate-account?token=

I upgraded to 1.3.1 one hour ago. not working.

Good job glewe, is a cool tool :)

**Comment by glewe** [comment]
Hi @stezam ,
I tried on my end and the token is set. The mail is sent too and activation worked.
What are the exact steps you did?
Best regards,
George

**Comment by stezam** [comment]
Hi Glewe
Thank you for your promp reply.

This is what I am doing.
1. Login with an admin account 
2. Using one of the seeded users in this case dduck
3. go to the edit tab and update the password and group etc
4. When I try to login with the updated user I get the message to have the system to resend the activation email
5. Receive the email (using Mail Trap for now.  But therer is no token assigned to the parameter token=

Thank you

**Comment by glewe** [comment]
Hi @stezam ,
the reason for that is that the user is not active yet. I actually forgot to put that setting onto the user edit dialog.
I done that now in 1.4.0.
Best regards,
George

**Comment by stezam** [comment]
Thank you will try that tomorrow
